### PR TITLE
Task 121 switch from travis to git hub actions

### PR DESCRIPTION
**Pull request by LorenzoBettini**
I had many problems running SWTBot tests in GitHub Actions: the job simply hangs indefinitely and I had to cancel... I suspect there are several problems with the GTK version: we build using Oxygen that is really old and I guess it does not work with recent versions of GTK, or, at least, SWTBot cannot handle such combinations. In Travis we were using Trusty (14.04) but the oldest version provided by GitHub Actions is 16.04, which does not work either with our tests. Unfortunately, I cannot understand what's going on since after some time the job simply hangs. What I can tell for sure is that most of those SWTBot tests fail on my machine too (both from Eclipse and from the command line). We also said in the past that those tests were rather flaky...

For the moment, I had to disable those tests. I suggest we open a new issue and try to deal with those tests. I guess most of them bring no value so we can remove them.

I also cleaned up the TP a bit, by using the latest versions. I guess in the near future we should switch to a newer TP as well.

@echebbi please let me know.

P.S. Codecov and SonarCloud are not enabled yet, and I suggest we postpone that as well.

### CODE REVIEW

**Comment by echebbi** [comment]
> I had many problems running SWTBot tests in GitHub Actions: the job simply hangs indefinitely and I had to cancel... I suspect there are several problems with the GTK version

I didn't forsee it but that was to be expected, I guess.

> What I can tell for sure is that most of those SWTBot tests fail on my machine too (both from Eclipse and from the command line). We also said in the past that those tests were rather flaky...

Yeah, you musn't touch anything during the tests and they still may fail randomly (#81). I run the tests on my machine yesterday which proves they can still pass.

> For the moment, I had to disable those tests. I suggest we open a new issue and try to deal with those tests. I guess most of them bring no value so we can remove them.

Likely the best option. Some tests are useful though because they check lots of different options and parameters but we should at least be able to turn those relevant tests into non-UI tests.

> I also cleaned up the TP a bit, by using the latest versions. I guess in the near future we should switch to a newer TP as well.

I'm completely open to such a switch, we just have to discuss what is the oldest version of Eclipse IDE we want to support.

> Codecov and SonarCloud are not enabled yet, and I suggest we postpone that as well.

They used to work but SonarCloud broke a while ago and I never took the time to fix it (#105). Now they don't even support Java 8 anymore, causing the whole pipeline to fail. In the other PR I [disabled it](https://github.com/pitest/pitclipse/pull/124/commits/8485939fbbf5097b02d196d4ac183dd07d200209) until we can fix it.

**Comment by LorenzoBettini** [comment]
@echebbi so if it's OK I'd merge it

**Comment by LorenzoBettini** [comment]
@echebbi I created and pushed a Git tag for the new release, but on GitHub there's still the release 2.1.0 tagged as "Latest" and I don't know how to fix that...

**Comment by echebbi** [comment]
@LorenzoBettini Releases have to be created manually. First go to https://github.com/pitest/pitclipse/releases (accessible from Pitclipse's main page > _Releases_) then click on _Draft a new release_. For future tags we may want to automate thanks to the [GitHub Create Tag Release](https://github.com/marketplace/actions/github-create-tag-release) Action.

**Comment by LorenzoBettini** [comment]
OK, for the moment I've promoted the release created with the tag as the latest one.

By the way, currently releasing a new update site from GitHub Actions is still not enabled.
For the moment, we administrators can publish a new update site from our computer:

```
mvn deploy -Prelease-composite
```

or, to publish a new snapshot:

```
mvn deploy -Prelease-composite,release-snapshots
```

During the git clone/push you might be asked for your password or SSH passphrase unless you have some keyring mechanism on your computer.

To publish from GitHub Actions we need a personal access token in the GitHub `pitest` organization. Or maybe it might be enough to create one for our own user and make it available at the organization level.

**Pull request merged**
