### PR TITLE
add missing icon transparency

### PR DESCRIPTION
**Pull request by Bananeweizen**
The icons in the tree view are not transparent. Convert to PNG (one of the GIFs _was_ already a wrongly named PNG) and remove background color.

### CODE REVIEW

**Comment by LorenzoBettini** [comment]
Thanks!

**Comment by ilMagnifico** [comment]
Screenshot 2023-03-04 at 10 08 55 PM
I'm using the last version, this icon is not yet transparent.

**Comment by LorenzoBettini** [comment]
Sorry, I forgot to make the release. I'll try to do that ASAP

**Comment by LorenzoBettini** [comment]
Version 2.2.1 has just been published.
Sorry for the delay

**Pull request merged**
