### PR TITLE
Store test launch configurations

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Since it is not completely clear how to run the tests from Eclipse.

For example, runner.tests must be run as Plug-in Tests; ui.tests must be
run using the org.eclipse.platform.ide (this increases chances of
success... though they are flaky anyway)

### CODE REVIEW

**Comment by echebbi** [comment]
That's a great idea, thank you. Would you mind updating the [CONTRIBUTING guide](https://github.com/pitest/pitclipse/blob/05ff24c662265b6a6bca32290c7b944504dcb620/CONTRIBUTING.md) to explain how to run these launch configurations? Not everyone is familiar with RCP development and I believe that a few sentences in section _How can I check that the tests still pass?_ may be helpful.

**Comment by LorenzoBettini** [comment]
@echebbi I've updated the guide in this PR, please have a look

**Comment by echebbi** [comment]
That's perfect, thanks

**Comment by LorenzoBettini** [comment]
So could you please merge this?

**Pull request merged**
