### PR TITLE
Correcting the default init from preferences

### PR DESCRIPTION
**Pull request by JKutscha**
The current init of the preferences is broken and writes a wrong value in the mutators preference.

### CODE REVIEW

**Comment by LorenzoBettini** [comment]
That's something I had spotted in the past myself but never fixed that because I couldn't figure out how the bug actually revealed itself. How did you find the wrong behavior?

**Comment by JKutscha** [comment]
I found this bug, after resetting my test workspace.

**Comment by LorenzoBettini** [comment]
> I found this bug, after resetting my test workspace.

and what's the value it writes?

**Comment by JKutscha** [comment]
> 
> and what's the value it writes?

I‘m not sure, if I understand. What value are you referring to?

**Comment by LorenzoBettini** [comment]
> > and what's the value it writes?
> 
> I‘m not sure, if I understand. What value are you referring to?

I mean, how have you detected that it was setting the wrong value?
When I opened my fresh workspace it was using the DEFAULT mutators (but I'm talking about the current released version, not the one under development), that's why when I spotted that strange setting I did not think about a bug since the behavior, in the end, was the expected one...

**Comment by JKutscha** [comment]
> 
> I mean, how have you detected that it was setting the wrong value?
> When I opened my fresh workspace it was using the DEFAULT mutators (but I'm talking about the current released version, not the one under development), that's why when I spotted that strange setting I did not think about a bug since the behavior, in the end, was the expected one...

The value was set to "defaultMutators" instead of the DEFAULTS.
I think this is the result of the rework I did on the preferences and the mutators itself.

**Comment by LorenzoBettini** [comment]
OK, merged! Thanks!

**Pull request merged**
