### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by LorenzoBettini**
PitclipseService was used only in its own PitclipseServiceTest so I removed them both

### CODE REVIEW

**Comment by LorenzoBettini** [comment]
@echebbi what do you think?

**Comment by LorenzoBettini** [comment]
@echebbi I'd like to merge it is that OK?

**Comment by echebbi** [comment]
@LorenzoBettini if the files aren't actually used, why did you moved them instead of merely removed them?

**Comment by LorenzoBettini** [comment]
> @LorenzoBettini if the files aren't actually used, why did you moved them instead of merely removed them?

I just wanted to be sure ;)
if you prefer I'll remove them directly

**Comment by echebbi** [comment]
Yes, I think it's cleaner that way. If those files ever end up appearing useful we'll still be able to recover them with Git.

**Pull request merged**
